package testBed;

/**
 *
 * @author Andrew Thompson
 */
public class MainWindow extends javax.swing.JFrame {

	private AttendanceDriverTest driver;
	/**
	 * Creates new form MainWindow
	 * @param driver 
	 */
	public MainWindow() {
		driver = new AttendanceDriverTest();
		driver.run();
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		bubbleButton = new javax.swing.JButton();
		searchButton = new javax.swing.JButton();
		hitListButton = new javax.swing.JButton();
		dateDrop = new javax.swing.JComboBox();
		membersDrop = new javax.swing.JComboBox();
		lateCheck = new javax.swing.JCheckBox();
		absentCheck = new javax.swing.JCheckBox();
		totalCheck = new javax.swing.JCheckBox();
		textScrollPane = new javax.swing.JScrollPane();
		outputPane = new javax.swing.JTextPane();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		bubbleButton.setText("Bubble");
		bubbleButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bubbleButtonActionPerformed(evt);
			}
		});

		searchButton.setText("Search");
		searchButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				searchButtonActionPerformed(evt);
			}
		});

		hitListButton.setText("Hit List");
		hitListButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				hitListButtonActionPerformed(evt);
			}
		});

		dateDrop.setModel(new javax.swing.DefaultComboBoxModel(driver.getDateList()));
		dateDrop.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				dateDropActionPerformed(evt);
			}
		});

		membersDrop.setModel(new javax.swing.DefaultComboBoxModel(driver.getMemberList()));
		membersDrop.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				membersDropActionPerformed(evt);
			}
		});

		lateCheck.setText("Late");
		lateCheck.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				lateCheckActionPerformed(evt);
			}
		});

		absentCheck.setText("Absent");
		absentCheck.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				absentCheckActionPerformed(evt);
			}
		});

		totalCheck.setText("Total");
		totalCheck.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				totalCheckActionPerformed(evt);
			}
		});

		outputPane.setEditable(false);
		outputPane.setText("Hello, oh Supreme Secretary. For maximum operatitas, please make sure this application is in your attendance folder.\nMake sure your excel spreadsheet is saved as \"Men's Glee Club Attendance.xls\" in Excel's compatibility mode (2007 mode).\nLastly, make sure that your colors remain consistant. If one Ignore-Date color is a lighter or darker shade, it will not be registered.\n\nIn your good service,\nDennis\nOfficial Artificial Intelligence of the Wheaton College Men's Glee Club.");
		textScrollPane.setViewportView(outputPane);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(textScrollPane)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(dateDrop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(bubbleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(hitListButton, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
														.addComponent(membersDrop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGroup(layout.createSequentialGroup()
																		.addComponent(lateCheck)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(absentCheck)
																		.addGap(18, 18, 18)
																		.addComponent(totalCheck)))))
																		.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(dateDrop)
								.addComponent(membersDrop, javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(lateCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(absentCheck)
										.addComponent(totalCheck)))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(textScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
												.addComponent(bubbleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(hitListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addContainerGap())
				);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void bubbleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubbleButtonActionPerformed
		writeToScreen(driver.getBubble());
	}//GEN-LAST:event_bubbleButtonActionPerformed

	private void hitListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitListButtonActionPerformed
		writeToScreen(driver.getHitList());
	}//GEN-LAST:event_hitListButtonActionPerformed

	private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
		if (!dateDrop.getSelectedItem().equals("All Dates")){
			if(!(lateCheck.getSelectedObjects() != null) && !(absentCheck.getSelectedObjects() != null)){
				writeToScreen(driver.getDateLate(dateDrop.getSelectedItem().toString())+driver.getDateAbsent(dateDrop.getSelectedItem().toString()));
			}
			if((lateCheck.getSelectedObjects() != null) && (absentCheck.getSelectedObjects() != null)){
				writeToScreen(driver.getDateLate(dateDrop.getSelectedItem().toString())+driver.getDateAbsent(dateDrop.getSelectedItem().toString()));
			}
			else if(lateCheck.getSelectedObjects() != null){
				writeToScreen(driver.getDateLate(dateDrop.getSelectedItem().toString()));
			}
			else if(absentCheck.getSelectedObjects() != null){
				writeToScreen(driver.getDateAbsent(dateDrop.getSelectedItem().toString()));
			}
		}else if (membersDrop.getSelectedItem().equals("All Members"))
			writeToScreen(driver.getMembersReport());
		else{
			if(lateCheck.getSelectedObjects() == null && absentCheck.getSelectedObjects() == null){
				writeToScreen(driver.getMemberAttendanceReport(membersDrop.getSelectedItem().toString()));
			}
			if(lateCheck.getSelectedObjects() != null && absentCheck.getSelectedObjects() != null){
				writeToScreen(driver.getMemberLateReport(membersDrop.getSelectedItem().toString())+"\n"+driver.getMemberAbsentReport(membersDrop.getSelectedItem().toString()));
			}
			else if(lateCheck.getSelectedObjects() != null)
				writeToScreen(driver.getMemberLateReport(membersDrop.getSelectedItem().toString()));
			else if(absentCheck.getSelectedObjects() != null)
				writeToScreen(driver.getMemberAbsentReport(membersDrop.getSelectedItem().toString()));
			else if(totalCheck.getSelectedObjects() != null)
				writeToScreen(driver.getMemberTotalReport(membersDrop.getSelectedItem().toString()));
		}
	}//GEN-LAST:event_searchButtonActionPerformed

	private void dateDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateDropActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_dateDropActionPerformed

	private void membersDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membersDropActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_membersDropActionPerformed

	private void lateCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lateCheckActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_lateCheckActionPerformed

	private void absentCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absentCheckActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_absentCheckActionPerformed

	private void totalCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalCheckActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_totalCheckActionPerformed
	private void writeToScreen(String display){
		outputPane.setText(display);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainWindow().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JCheckBox absentCheck;
	private javax.swing.JButton bubbleButton;
	private javax.swing.JComboBox dateDrop;
	private javax.swing.JButton hitListButton;
	private javax.swing.JCheckBox lateCheck;
	private javax.swing.JComboBox membersDrop;
	private javax.swing.JTextPane outputPane;
	private javax.swing.JButton searchButton;
	private javax.swing.JScrollPane textScrollPane;
	private javax.swing.JCheckBox totalCheck;
	// End of variables declaration//GEN-END:variables
}
